name: docs
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: |
          . .venv/bin/activate
          isort src tests
          flake8 src tests
          bandit -r src
          mypy src
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          . .venv/bin/activate
          pytest
  doc:
    runs-on: ubuntu-latest
    steps:
      - run: |
          . .venv/bin/activate
          rm -rf docs/*
          sphinx-apidoc -f -o sphinx/source/piest src/piest
          make dirhtml -C sphinx
          cd docs
          mv dirhtml/* .
          rm -r dirhtml
